name: Deployment

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker-build:
    uses: onlydustxyz/cicd/.github/workflows/docker-workflow.yml@main
    with:
      image_name: themerge-nft-api
      image_tag: latest
      dockerfile: nodejs
      datadog_label: '[{"source": "themerge-nft", "service": "api"}]'
    secrets: inherit
